---
- name: Install Ubuntu dependencies
  sudo: yes
  yum: name={{ item }} state=installed
  when: ansible_os_family == 'Ubuntu'
  with_items:
    - git
    - make
    # Required by GNU C -> Memprof
    - binutils
    - texinfo
    - gawk
    - sed
    - autoconf
    - build-essential
    - php-pear
    # Required by opcode.yml/APC
    - libpcre3-dev

- name: Create temporary directory
  file: state=directory path={{ liara_temp_dir }}

- name: Cleanup all temporary files
  command: rm -rf {{ liara_temp_dir }}
